### ISSUE TITLE
blaze-meta config shouldn't be inside Meteor.startup

### ISSUE THREAD

**Issue by semikolon** [Differential/meteor-boilerplate#43]
The config code in both/router/meta.js shouldn't be wrapped in Meteor.startup. If it is, I need to run setTitle again to update title. If I DON'T run setTitle anywhere, the title will be "Default Title" - despite my custom title in meta.js

(Hope I'm making myself clear.)

**Comment by nickw** [comment]
Hmm, I'm not following. Isn't the point of blaze-meta to have a default title that gets overridden in each route?

**Comment by semikolon** [comment]
I'd like to override the default default title, to have my own default title. If I set that in the config on meteor startup then it's not applied. It's gotta be configured "before startup".

**Comment by rgoomar** [comment]
Ah... I see what you mean now @semikolon . 
```javascript
// Gets you 'Default Title' every time for those that do not have titles set instead of 'My Project'
Meteor.startup(function() {
  if(Meteor.isClient) {
    Meta.config({
      options: {
        // Meteor.settings[Meteor.settings.environment].public.meta.title
        title: 'My Project',
        suffix: 'Project Title'
      }
    });
  }
});
```
But...
```
// Gets you 'My Project' as a default title not 'Default Title'
if(Meteor.isClient) {
  Meta.config({
    options: {
      // Meteor.settings[Meteor.settings.environment].public.meta.title
      title: 'My Project',
      suffix: 'Project Title'
    }
  });
}
```
Also, I tested it out and if you set the titles in the router controllers, it overrides this default title. So, it works as it should. 

@nickw that should clear things up.
