### ISSUE TITLE
mechanism to upgrade Bootstrap?

### ISSUE THREAD

**Issue by stocksp** [Differential/meteor-boilerplate#44]
I need 3.3.2..
Did I do this correctly?
Replaced bootstrap.js in client/compatibility with the unminified one in the downloaded zip from the bootstrap website.
Removed the stylesheets/base/lib/bootstrap folder contents.
Replaced the above contents with the latest source.
Renamed all the '.less' files to '.import.less'
Did the same (made the import statements reference the new file names) inside bootstrap.import.less and mixins.import.less.

Seems to be working ... but I don't know what I'm doing as I'm new to Meteor!

Your template has been a big help!

P:)

**Comment by rgoomar** [comment]
Yes that is the correct procedure to update bootstrap files. I didn't realize it was outdated actually. I'll try to update it soon.

**Comment by rgoomar** [comment]
Updated in 23a71cd
