### ISSUE TITLE
Boilerplate setup leaves .meteor/.id unchanged

### ISSUE THREAD

**Issue by nickbenes** [Differential/meteor-boilerplate#48]
Not sure if this is an issue, but I'm trying out this boilerplate and am a little worried that my `.meteor\.id` will be identical to hundreds of other apps. Any best practices for generating a new one?

Otherwise, liking the setup so far. Thanks!

**Comment by antarexis** [comment]
Just remove the file, Meteor will create a new one for you.

I think this isn't an issue so you should close this one.
