### ISSUE TITLE
Outdated package? MUP issues

### ISSUE THREAD

**Issue by jhmacdon** [Differential/meteor-boilerplate#53]
So this works fine on my local machine, but when it in minified and deployed using mup, it just displays the iron:router main page. Errors at the bottom include:

<code>
Uncaught TypeError: Cannot read property 'helpers' of undefined
</code>
<code>
Uncaught TypeError: Cannot read property 'ServiceConfiguration' of undefined
</code>

**Comment by compoundtherapy** [comment]
Hey after 1/2 year of growing fond of mup and its smooth deploys, we have just started getting this same result:
  works fine on localhost
  deploy using mup and get no errors except for the 2 uncaught TypeErrors listed above
  only iron:router main page background displays. Basic initialization of app appears to be running, but no display?????
We are using ubuntu 14.04.2 LTS with node v0.10.36 on this instance. 
matb33:collection-hooks          0.7.13  Extends Mongo.Collection with before/after hooks for insert/update/remove/fi...
meteor-platform                  1.2.2  Include a standard set of Meteor packages in your app
meteorhacks:kadira               2.20.2* Performance Monitoring for Meteor
meteorhacks:kadira-profiler      1.1.0  CPU Profiler for Kadira
meteorhacks:ssr                  2.1.2  Server Side Rendering for Meteor with Blaze
mizzao:bootboxjs                 4.4.0  Programmatic dialog boxes using Twitter's bootstrap modals
mizzao:bootstrap-3               3.3.1_1  HTML, CSS, and JS framework for developing responsive, mobile first project...
mizzao:user-status               0.6.4  User connection and idle state tracking for Meteor
momentjs:moment                  2.10.3  Moment.js (official): parse, validate, manipulate, and display dates - offic...
mrt:accounts-t9n                 0.0.13  Translations for the meteor account's error messages
mrt:accounts-ui-bootstrap-3      0.3.3  Bootstrap styled version of login widgets
and other packages

Any ideas would be great!!!!! 
We are attempting to lock down our product for demonstrations to customers and then this issue has definitely stopped us in our tracks. Thank you

**Comment by compoundtherapy** [comment]
Our issue was fixed by replacing deprecated Route.map with Route.route.

**Comment by lehtu** [comment]
Our isses was fixed by installing all used packages. Had few packages that was used in code, but wasnt installed on this project version on localhost, though it was still working on localhost, but not on server. Added missing packages and now it works on server too. Didn't much complain about missing packakges..
